package sop_corba;


/**
* sop_corba/_LoguearIntStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaces.idl
* viernes 2 de agosto de 2019 08:07:24 PM COT
*/

public class _LoguearIntStub extends org.omg.CORBA.portable.ObjectImpl implements sop_corba.LoguearInt
{

  public sop_corba.RespuestaISDTO iniciarSesion (sop_corba.IniciarSesionDTO datosIS)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("iniciarSesion", true);
                sop_corba.IniciarSesionDTOHelper.write ($out, datosIS);
                $in = _invoke ($out);
                sop_corba.RespuestaISDTO $result = sop_corba.RespuestaISDTOHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return iniciarSesion (datosIS        );
            } finally {
                _releaseReply ($in);
            }
  } // iniciarSesion

  public sop_corba.RespuestaGDTO cambiarContrasenia (sop_corba.CambioContraseniaDTO datosCC)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("cambiarContrasenia", true);
                sop_corba.CambioContraseniaDTOHelper.write ($out, datosCC);
                $in = _invoke ($out);
                sop_corba.RespuestaGDTO $result = sop_corba.RespuestaGDTOHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return cambiarContrasenia (datosCC        );
            } finally {
                _releaseReply ($in);
            }
  } // cambiarContrasenia

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/LoguearInt:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _LoguearIntStub
