package sop_corba;


/**
* sop_corba/_OperacionesEDIntStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaces.idl
* viernes 2 de agosto de 2019 08:07:24 PM COT
*/

public class _OperacionesEDIntStub extends org.omg.CORBA.portable.ObjectImpl implements sop_corba.OperacionesEDInt
{

  public sop_corba.AnteproyectoDTO buscarAnteproyecto (String codigoAnteproyecto)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("buscarAnteproyecto", true);
                $out.write_string (codigoAnteproyecto);
                $in = _invoke ($out);
                sop_corba.AnteproyectoDTO $result = sop_corba.AnteproyectoDTOHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return buscarAnteproyecto (codigoAnteproyecto        );
            } finally {
                _releaseReply ($in);
            }
  } // buscarAnteproyecto

  public sop_corba.AnteproyectoSimpleDTO[] listarAnteproyectos ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("listarAnteproyectos", true);
                $in = _invoke ($out);
                sop_corba.AnteproyectoSimpleDTO $result[] = sop_corba.ListaAnteproyectosHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return listarAnteproyectos (        );
            } finally {
                _releaseReply ($in);
            }
  } // listarAnteproyectos

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/OperacionesEDInt:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _OperacionesEDIntStub
