package sop_corba;


/**
* sop_corba/AgregarConceptoAnteproyectoDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaces.idl
* viernes 2 de agosto de 2019 08:07:24 PM COT
*/

public final class AgregarConceptoAnteproyectoDTO implements org.omg.CORBA.portable.IDLEntity
{
  public String concepto = null;
  public String codigoAnteproyecto = null;
  public String nombreEvaluador = null;

  public AgregarConceptoAnteproyectoDTO ()
  {
  } // ctor

  public AgregarConceptoAnteproyectoDTO (String _concepto, String _codigoAnteproyecto, String _nombreEvaluador)
  {
    concepto = _concepto;
    codigoAnteproyecto = _codigoAnteproyecto;
    nombreEvaluador = _nombreEvaluador;
  } // ctor

    public String getConcepto() {
        return concepto;
    }

    public void setConcepto(String concepto) {
        this.concepto = concepto;
    }

    public String getCodigoAnteproyecto() {
        return codigoAnteproyecto;
    }

    public void setCodigoAnteproyecto(String codigoAnteproyecto) {
        this.codigoAnteproyecto = codigoAnteproyecto;
    }

    public String getNombreEvaluador() {
        return nombreEvaluador;
    }

    public void setNombreEvaluador(String nombreEvaluador) {
        this.nombreEvaluador = nombreEvaluador;
    }
  
  

} // class AgregarConceptoAnteproyectoDTO
