package sop_corba;


/**
* sop_corba/AgregarConceptoAnteproyectoDTOHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaces.idl
* viernes 2 de agosto de 2019 08:07:24 PM COT
*/

abstract public class AgregarConceptoAnteproyectoDTOHelper
{
  private static String  _id = "IDL:sop_corba/AgregarConceptoAnteproyectoDTO:1.0";

  public static void insert (org.omg.CORBA.Any a, sop_corba.AgregarConceptoAnteproyectoDTO that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static sop_corba.AgregarConceptoAnteproyectoDTO extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [3];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "concepto",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "codigoAnteproyecto",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "nombreEvaluador",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (sop_corba.AgregarConceptoAnteproyectoDTOHelper.id (), "AgregarConceptoAnteproyectoDTO", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static sop_corba.AgregarConceptoAnteproyectoDTO read (org.omg.CORBA.portable.InputStream istream)
  {
    sop_corba.AgregarConceptoAnteproyectoDTO value = new sop_corba.AgregarConceptoAnteproyectoDTO ();
    value.concepto = istream.read_string ();
    value.codigoAnteproyecto = istream.read_string ();
    value.nombreEvaluador = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, sop_corba.AgregarConceptoAnteproyectoDTO value)
  {
    ostream.write_string (value.concepto);
    ostream.write_string (value.codigoAnteproyecto);
    ostream.write_string (value.nombreEvaluador);
  }

}
