package sop_corba;


/**
* sop_corba/AnteproyectoDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaces.idl
* viernes 2 de agosto de 2019 08:07:24 PM COT
*/

public final class AnteproyectoDTO implements org.omg.CORBA.portable.IDLEntity
{
  public String modalidad = null;
  public String titulo = null;
  public String codigo = null;
  public String nombreEstudiante1 = null;
  public String nombreEstudiante2 = null;
  public String nombreDirector = null;
  public String nombreCoDirector = null;
  public String fechaRegistro = null;
  public String fechaAprobacion = null;
  public int concepto = (int)0;
  public int estado = (int)0;
  public int numeroRevision = (int)0;

  public AnteproyectoDTO ()
  {
  } // ctor

  public AnteproyectoDTO (String _modalidad, String _titulo, String _codigo, String _nombreEstudiante1, String _nombreEstudiante2, String _nombreDirector, String _nombreCoDirector, String _fechaRegistro, String _fechaAprobacion, int _concepto, int _estado, int _numeroRevision)
  {
    modalidad = _modalidad;
    titulo = _titulo;
    codigo = _codigo;
    nombreEstudiante1 = _nombreEstudiante1;
    nombreEstudiante2 = _nombreEstudiante2;
    nombreDirector = _nombreDirector;
    nombreCoDirector = _nombreCoDirector;
    fechaRegistro = _fechaRegistro;
    fechaAprobacion = _fechaAprobacion;
    concepto = _concepto;
    estado = _estado;
    numeroRevision = _numeroRevision;
  } // ctor

    public String getModalidad() {
        return modalidad;
    }

    public void setModalidad(String modalidad) {
        this.modalidad = modalidad;
    }

    public String getTitulo() {
        return titulo;
    }

    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    public String getCodigo() {
        return codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public String getNombreEstudiante1() {
        return nombreEstudiante1;
    }

    public void setNombreEstudiante1(String nombreEstudiante1) {
        this.nombreEstudiante1 = nombreEstudiante1;
    }

    public String getNombreEstudiante2() {
        return nombreEstudiante2;
    }

    public void setNombreEstudiante2(String nombreEstudiante2) {
        this.nombreEstudiante2 = nombreEstudiante2;
    }

    public String getNombreDirector() {
        return nombreDirector;
    }

    public void setNombreDirector(String nombreDirector) {
        this.nombreDirector = nombreDirector;
    }

    public String getNombreCoDirector() {
        return nombreCoDirector;
    }

    public void setNombreCoDirector(String nombreCoDirector) {
        this.nombreCoDirector = nombreCoDirector;
    }

    public String getFechaRegistro() {
        return fechaRegistro;
    }

    public void setFechaRegistro(String fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

    public String getFechaAprobacion() {
        return fechaAprobacion;
    }

    public void setFechaAprobacion(String fechaAprobacion) {
        this.fechaAprobacion = fechaAprobacion;
    }

    public int getConcepto() {
        return concepto;
    }

    public void setConcepto(int concepto) {
        this.concepto = concepto;
    }

    public int getEstado() {
        return estado;
    }

    public void setEstado(int estado) {
        this.estado = estado;
    }

    public int getNumeroRevision() {
        return numeroRevision;
    }

    public void setNumeroRevision(int numeroRevision) {
        this.numeroRevision = numeroRevision;
    }
  
  

} // class AnteproyectoDTO
