package sop_corba;


/**
* sop_corba/AnteproyectoCompletoDTOHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaces.idl
* viernes 2 de agosto de 2019 08:07:24 PM COT
*/

abstract public class AnteproyectoCompletoDTOHelper
{
  private static String  _id = "IDL:sop_corba/AnteproyectoCompletoDTO:1.0";

  public static void insert (org.omg.CORBA.Any a, sop_corba.AnteproyectoCompletoDTO that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static sop_corba.AnteproyectoCompletoDTO extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = sop_corba.AnteproyectoDTOHelper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "anteproyecto",
            _tcOf_members0,
            null);
          _tcOf_members0 = sop_corba.EvaluadoresDTOHelper.type ();
          _members0[1] = new org.omg.CORBA.StructMember (
            "evaluadores",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (sop_corba.AnteproyectoCompletoDTOHelper.id (), "AnteproyectoCompletoDTO", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static sop_corba.AnteproyectoCompletoDTO read (org.omg.CORBA.portable.InputStream istream)
  {
    sop_corba.AnteproyectoCompletoDTO value = new sop_corba.AnteproyectoCompletoDTO ();
    value.anteproyecto = sop_corba.AnteproyectoDTOHelper.read (istream);
    value.evaluadores = sop_corba.EvaluadoresDTOHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, sop_corba.AnteproyectoCompletoDTO value)
  {
    sop_corba.AnteproyectoDTOHelper.write (ostream, value.anteproyecto);
    sop_corba.EvaluadoresDTOHelper.write (ostream, value.evaluadores);
  }

}
