package sop_corba;


/**
* sop_corba/AnteproyectoSimpleDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaces.idl
* viernes 2 de agosto de 2019 08:07:24 PM COT
*/

public final class AnteproyectoSimpleDTO implements org.omg.CORBA.portable.IDLEntity
{
  public String Codigo = null;
  public String Titulo = null;

  public AnteproyectoSimpleDTO ()
  {
  } // ctor

  public AnteproyectoSimpleDTO (String _Codigo, String _Titulo)
  {
    Codigo = _Codigo;
    Titulo = _Titulo;
  } // ctor

    public String getCodigo() {
        return Codigo;
    }

    public void setCodigo(String Codigo) {
        this.Codigo = Codigo;
    }

    public String getTitulo() {
        return Titulo;
    }

    public void setTitulo(String Titulo) {
        this.Titulo = Titulo;
    }
  
  

} // class AnteproyectoSimpleDTO
