package sop_corba;


/**
* sop_corba/AnteproyectoDTOHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaces.idl
* viernes 2 de agosto de 2019 08:07:24 PM COT
*/

abstract public class AnteproyectoDTOHelper
{
  private static String  _id = "IDL:sop_corba/AnteproyectoDTO:1.0";

  public static void insert (org.omg.CORBA.Any a, sop_corba.AnteproyectoDTO that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static sop_corba.AnteproyectoDTO extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [12];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "modalidad",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "titulo",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "codigo",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "nombreEstudiante1",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[4] = new org.omg.CORBA.StructMember (
            "nombreEstudiante2",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[5] = new org.omg.CORBA.StructMember (
            "nombreDirector",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[6] = new org.omg.CORBA.StructMember (
            "nombreCoDirector",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[7] = new org.omg.CORBA.StructMember (
            "fechaRegistro",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[8] = new org.omg.CORBA.StructMember (
            "fechaAprobacion",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[9] = new org.omg.CORBA.StructMember (
            "concepto",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[10] = new org.omg.CORBA.StructMember (
            "estado",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[11] = new org.omg.CORBA.StructMember (
            "numeroRevision",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (sop_corba.AnteproyectoDTOHelper.id (), "AnteproyectoDTO", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static sop_corba.AnteproyectoDTO read (org.omg.CORBA.portable.InputStream istream)
  {
    sop_corba.AnteproyectoDTO value = new sop_corba.AnteproyectoDTO ();
    value.modalidad = istream.read_string ();
    value.titulo = istream.read_string ();
    value.codigo = istream.read_string ();
    value.nombreEstudiante1 = istream.read_string ();
    value.nombreEstudiante2 = istream.read_string ();
    value.nombreDirector = istream.read_string ();
    value.nombreCoDirector = istream.read_string ();
    value.fechaRegistro = istream.read_string ();
    value.fechaAprobacion = istream.read_string ();
    value.concepto = istream.read_long ();
    value.estado = istream.read_long ();
    value.numeroRevision = istream.read_long ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, sop_corba.AnteproyectoDTO value)
  {
    ostream.write_string (value.modalidad);
    ostream.write_string (value.titulo);
    ostream.write_string (value.codigo);
    ostream.write_string (value.nombreEstudiante1);
    ostream.write_string (value.nombreEstudiante2);
    ostream.write_string (value.nombreDirector);
    ostream.write_string (value.nombreCoDirector);
    ostream.write_string (value.fechaRegistro);
    ostream.write_string (value.fechaAprobacion);
    ostream.write_long (value.concepto);
    ostream.write_long (value.estado);
    ostream.write_long (value.numeroRevision);
  }

}
