package sop_corba;


/**
* sop_corba/CambioContraseniaDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaces.idl
* viernes 2 de agosto de 2019 08:07:24 PM COT
*/

public final class CambioContraseniaDTO implements org.omg.CORBA.portable.IDLEntity
{
  public sop_corba.IniciarSesionDTO datosUsuario = null;
  public String nuveaContrasenia = null;

  public CambioContraseniaDTO ()
  {
  } // ctor

  public CambioContraseniaDTO (sop_corba.IniciarSesionDTO _datosUsuario, String _nuveaContrasenia)
  {
    datosUsuario = _datosUsuario;
    nuveaContrasenia = _nuveaContrasenia;
  } // ctor

    public IniciarSesionDTO getDatosUsuario() {
        return datosUsuario;
    }

    public void setDatosUsuario(IniciarSesionDTO datosUsuario) {
        this.datosUsuario = datosUsuario;
    }

    public String getNuveaContrasenia() {
        return nuveaContrasenia;
    }

    public void setNuveaContrasenia(String nuveaContrasenia) {
        this.nuveaContrasenia = nuveaContrasenia;
    }
  

} // class CambioContraseniaDTO
