package sop_corba;


/**
* sop_corba/EvaluadoresDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaces.idl
* viernes 2 de agosto de 2019 08:07:24 PM COT
*/

public final class EvaluadoresDTO implements org.omg.CORBA.portable.IDLEntity
{
  public String codigoAnteproyecto = null;
  public String nombreEvaluador1 = null;
  public String conceptoEvaluador1 = null;
  public String fechaRevision1 = null;
  public String nombreEvaluador2 = null;
  public String conceptoEvaluador2 = null;
  public String fechaRevision2 = null;

  public EvaluadoresDTO ()
  {
  } // ctor

  public EvaluadoresDTO (String _codigoAnteproyecto, String _nombreEvaluador1, String _conceptoEvaluador1, String _fechaRevision1, String _nombreEvaluador2, String _conceptoEvaluador2, String _fechaRevision2)
  {
    codigoAnteproyecto = _codigoAnteproyecto;
    nombreEvaluador1 = _nombreEvaluador1;
    conceptoEvaluador1 = _conceptoEvaluador1;
    fechaRevision1 = _fechaRevision1;
    nombreEvaluador2 = _nombreEvaluador2;
    conceptoEvaluador2 = _conceptoEvaluador2;
    fechaRevision2 = _fechaRevision2;
  } // ctor

    public String getCodigoAnteproyecto() {
        return codigoAnteproyecto;
    }

    public void setCodigoAnteproyecto(String codigoAnteproyecto) {
        this.codigoAnteproyecto = codigoAnteproyecto;
    }

    public String getNombreEvaluador1() {
        return nombreEvaluador1;
    }

    public void setNombreEvaluador1(String nombreEvaluador1) {
        this.nombreEvaluador1 = nombreEvaluador1;
    }

    public String getConceptoEvaluador1() {
        return conceptoEvaluador1;
    }

    public void setConceptoEvaluador1(String conceptoEvaluador1) {
        this.conceptoEvaluador1 = conceptoEvaluador1;
    }

    public String getFechaRevision1() {
        return fechaRevision1;
    }

    public void setFechaRevision1(String fechaRevision1) {
        this.fechaRevision1 = fechaRevision1;
    }

    public String getNombreEvaluador2() {
        return nombreEvaluador2;
    }

    public void setNombreEvaluador2(String nombreEvaluador2) {
        this.nombreEvaluador2 = nombreEvaluador2;
    }

    public String getConceptoEvaluador2() {
        return conceptoEvaluador2;
    }

    public void setConceptoEvaluador2(String conceptoEvaluador2) {
        this.conceptoEvaluador2 = conceptoEvaluador2;
    }

    public String getFechaRevision2() {
        return fechaRevision2;
    }

    public void setFechaRevision2(String fechaRevision2) {
        this.fechaRevision2 = fechaRevision2;
    }
  
  

} // class EvaluadoresDTO
