package sop_corba;


/**
* sop_corba/IniciarSesionDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaces.idl
* viernes 2 de agosto de 2019 08:07:24 PM COT
*/

public final class IniciarSesionDTO implements org.omg.CORBA.portable.IDLEntity
{
  public String usuario = null;
  public String contrasenia = null;
  public sop_corba.UsuarioCllbckInt userCllbck = null;

  public IniciarSesionDTO ()
  {
  } // ctor

  public IniciarSesionDTO (String _usuario, String _contrasenia, sop_corba.UsuarioCllbckInt _userCllbck)
  {
    usuario = _usuario;
    contrasenia = _contrasenia;
    userCllbck = _userCllbck;
  } // ctor

    public String getUsuario() {
        return usuario;
    }

    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    public String getContrasenia() {
        return contrasenia;
    }

    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }

    public UsuarioCllbckInt getUserCllbck() {
        return userCllbck;
    }

    public void setUserCllbck(UsuarioCllbckInt userCllbck) {
        this.userCllbck = userCllbck;
    }
  
  

} // class IniciarSesionDTO
