package sop_corba;


/**
* sop_corba/LoguearIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaces.idl
* viernes 2 de agosto de 2019 08:07:24 PM COT
*/

public interface LoguearIntOperations 
{
  sop_corba.RespuestaISDTO iniciarSesion (sop_corba.IniciarSesionDTO datosIS);
  sop_corba.RespuestaGDTO cambiarContrasenia (sop_corba.CambioContraseniaDTO datosCC);
} // interface LoguearIntOperations
