package sop_corba;


/**
* sop_corba/MConceptoAnteproyectoDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaces.idl
* viernes 2 de agosto de 2019 08:07:24 PM COT
*/

public final class MConceptoAnteproyectoDTO implements org.omg.CORBA.portable.IDLEntity
{
  public String codigoAnteproyecto = null;
  public int nuevoConcepto = (int)0;

  public MConceptoAnteproyectoDTO ()
  {
  } // ctor

  public MConceptoAnteproyectoDTO (String _codigoAnteproyecto, int _nuevoConcepto)
  {
    codigoAnteproyecto = _codigoAnteproyecto;
    nuevoConcepto = _nuevoConcepto;
  } // ctor

    public String getCodigoAnteproyecto() {
        return codigoAnteproyecto;
    }

    public void setCodigoAnteproyecto(String codigoAnteproyecto) {
        this.codigoAnteproyecto = codigoAnteproyecto;
    }

    public int getNuevoConcepto() {
        return nuevoConcepto;
    }

    public void setNuevoConcepto(int nuevoConcepto) {
        this.nuevoConcepto = nuevoConcepto;
    }
  
  

} // class MConceptoAnteproyectoDTO
