package sop_corba;

/**
* sop_corba/OperacionesJDIntHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaces.idl
* viernes 2 de agosto de 2019 08:07:24 PM COT
*/

public final class OperacionesJDIntHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba.OperacionesJDInt value = null;

  public OperacionesJDIntHolder ()
  {
  }

  public OperacionesJDIntHolder (sop_corba.OperacionesJDInt initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba.OperacionesJDIntHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba.OperacionesJDIntHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba.OperacionesJDIntHelper.type ();
  }

}
