package sop_corba;


/**
* sop_corba/OperacionesEIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaces.idl
* viernes 2 de agosto de 2019 08:07:24 PM COT
*/

public interface OperacionesEIntOperations 
{
  sop_corba.RespuestaGDTO agregarConceptoAnteproyecto (sop_corba.AgregarConceptoAnteproyectoDTO datosAnteproyecto);
} // interface OperacionesEIntOperations
