package sop_corba;


/**
* sop_corba/OperacionesJDIntPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaces.idl
* viernes 2 de agosto de 2019 08:07:24 PM COT
*/

public abstract class OperacionesJDIntPOA extends org.omg.PortableServer.Servant
 implements sop_corba.OperacionesJDIntOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("registrarUsuario", new java.lang.Integer (0));
    _methods.put ("registrarAnteproyecto", new java.lang.Integer (1));
    _methods.put ("asignarEvaluadores", new java.lang.Integer (2));
    _methods.put ("buscarAnteproyceto", new java.lang.Integer (3));
    _methods.put ("modificarConceptoAnteproyecto", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // sop_corba/OperacionesJDInt/registrarUsuario
       {
         sop_corba.UsuarioDTO datosUser = sop_corba.UsuarioDTOHelper.read (in);
         sop_corba.RespuestaGDTO $result = null;
         $result = this.registrarUsuario (datosUser);
         out = $rh.createReply();
         sop_corba.RespuestaGDTOHelper.write (out, $result);
         break;
       }

       case 1:  // sop_corba/OperacionesJDInt/registrarAnteproyecto
       {
         sop_corba.AnteproyectoDTO datosAnteproyecto = sop_corba.AnteproyectoDTOHelper.read (in);
         sop_corba.RespuestaGDTO $result = null;
         $result = this.registrarAnteproyecto (datosAnteproyecto);
         out = $rh.createReply();
         sop_corba.RespuestaGDTOHelper.write (out, $result);
         break;
       }

       case 2:  // sop_corba/OperacionesJDInt/asignarEvaluadores
       {
         sop_corba.EvaluadoresDTO datosEvaluadores = sop_corba.EvaluadoresDTOHelper.read (in);
         sop_corba.RespuestaGDTO $result = null;
         $result = this.asignarEvaluadores (datosEvaluadores);
         out = $rh.createReply();
         sop_corba.RespuestaGDTOHelper.write (out, $result);
         break;
       }

       case 3:  // sop_corba/OperacionesJDInt/buscarAnteproyceto
       {
         String codigoAnteproyecto = in.read_string ();
         sop_corba.AnteproyectoCompletoDTO $result = null;
         $result = this.buscarAnteproyceto (codigoAnteproyecto);
         out = $rh.createReply();
         sop_corba.AnteproyectoCompletoDTOHelper.write (out, $result);
         break;
       }

       case 4:  // sop_corba/OperacionesJDInt/modificarConceptoAnteproyecto
       {
         sop_corba.MConceptoAnteproyectoDTO datosModificacion = sop_corba.MConceptoAnteproyectoDTOHelper.read (in);
         sop_corba.RespuestaGDTO $result = null;
         $result = this.modificarConceptoAnteproyecto (datosModificacion);
         out = $rh.createReply();
         sop_corba.RespuestaGDTOHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/OperacionesJDInt:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public OperacionesJDInt _this() 
  {
    return OperacionesJDIntHelper.narrow(
    super._this_object());
  }

  public OperacionesJDInt _this(org.omg.CORBA.ORB orb) 
  {
    return OperacionesJDIntHelper.narrow(
    super._this_object(orb));
  }


} // class OperacionesJDIntPOA
