package sop_corba;


/**
* sop_corba/OperacionesEDIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaces.idl
* viernes 2 de agosto de 2019 08:07:24 PM COT
*/

public interface OperacionesEDIntOperations 
{
  sop_corba.AnteproyectoDTO buscarAnteproyecto (String codigoAnteproyecto);
  sop_corba.AnteproyectoSimpleDTO[] listarAnteproyectos ();
} // interface OperacionesEDIntOperations
