package sop_corba;


/**
* sop_corba/OperacionesEDIntPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaces.idl
* viernes 2 de agosto de 2019 08:07:24 PM COT
*/

public abstract class OperacionesEDIntPOA extends org.omg.PortableServer.Servant
 implements sop_corba.OperacionesEDIntOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("buscarAnteproyecto", new java.lang.Integer (0));
    _methods.put ("listarAnteproyectos", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // sop_corba/OperacionesEDInt/buscarAnteproyecto
       {
         String codigoAnteproyecto = in.read_string ();
         sop_corba.AnteproyectoDTO $result = null;
         $result = this.buscarAnteproyecto (codigoAnteproyecto);
         out = $rh.createReply();
         sop_corba.AnteproyectoDTOHelper.write (out, $result);
         break;
       }

       case 1:  // sop_corba/OperacionesEDInt/listarAnteproyectos
       {
         sop_corba.AnteproyectoSimpleDTO $result[] = null;
         $result = this.listarAnteproyectos ();
         out = $rh.createReply();
         sop_corba.ListaAnteproyectosHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/OperacionesEDInt:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public OperacionesEDInt _this() 
  {
    return OperacionesEDIntHelper.narrow(
    super._this_object());
  }

  public OperacionesEDInt _this(org.omg.CORBA.ORB orb) 
  {
    return OperacionesEDIntHelper.narrow(
    super._this_object(orb));
  }


} // class OperacionesEDIntPOA
