package sop_corba;


/**
* sop_corba/OperacionesJDIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaces.idl
* viernes 2 de agosto de 2019 08:07:24 PM COT
*/

public interface OperacionesJDIntOperations 
{
  sop_corba.RespuestaGDTO registrarUsuario (sop_corba.UsuarioDTO datosUser);
  sop_corba.RespuestaGDTO registrarAnteproyecto (sop_corba.AnteproyectoDTO datosAnteproyecto);
  sop_corba.RespuestaGDTO asignarEvaluadores (sop_corba.EvaluadoresDTO datosEvaluadores);
  sop_corba.AnteproyectoCompletoDTO buscarAnteproyceto (String codigoAnteproyecto);
  sop_corba.RespuestaGDTO modificarConceptoAnteproyecto (sop_corba.MConceptoAnteproyectoDTO datosModificacion);
} // interface OperacionesJDIntOperations
