package sop_corba;


/**
* sop_corba/RespuestaISDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaces.idl
* viernes 2 de agosto de 2019 08:07:24 PM COT
*/

public final class RespuestaISDTO implements org.omg.CORBA.portable.IDLEntity
{
  public int tipoUser = (int)0;
  public String mensaje = null;

  public RespuestaISDTO ()
  {
  } // ctor

  public RespuestaISDTO (int _tipoUser, String _mensaje)
  {
    tipoUser = _tipoUser;
    mensaje = _mensaje;
  } // ctor

    public int getTipoUser() {
        return tipoUser;
    }

    public void setTipoUser(int tipoUser) {
        this.tipoUser = tipoUser;
    }

    public String getMensaje() {
        return mensaje;
    }

    public void setMensaje(String mensaje) {
        this.mensaje = mensaje;
    }
  
  

} // class RespuestaISDTO
