package sop_corba;


/**
* sop_corba/RespuestaGDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaces.idl
* viernes 2 de agosto de 2019 08:07:24 PM COT
*/

public final class RespuestaGDTO implements org.omg.CORBA.portable.IDLEntity
{
  public boolean operacionExito = false;
  public String mensaje = null;

  public RespuestaGDTO ()
  {
  } // ctor

  public RespuestaGDTO (boolean _operacionExito, String _mensaje)
  {
    operacionExito = _operacionExito;
    mensaje = _mensaje;
  } // ctor

    public boolean isOperacionExito() {
        return operacionExito;
    }

    public void setOperacionExito(boolean operacionExito) {
        this.operacionExito = operacionExito;
    }

    public String getMensaje() {
        return mensaje;
    }

    public void setMensaje(String mensaje) {
        this.mensaje = mensaje;
    }
  
  

} // class RespuestaGDTO
