package sop_corba;


/**
* sop_corba/UsuarioCllbckInt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaces.idl
* viernes 2 de agosto de 2019 08:07:24 PM COT
*/

public interface UsuarioCllbckInt extends UsuarioCllbckIntOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface UsuarioCllbckInt
