package sop_corba;


/**
* sop_corba/UsuarioDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaces.idl
* viernes 2 de agosto de 2019 08:07:24 PM COT
*/

public final class UsuarioDTO implements org.omg.CORBA.portable.IDLEntity
{
  public String nombresApellidos = null;
  public String identificacion = null;
  public String usuario = null;
  public String contrasenia = null;
  public int tipoUser = (int)0;

  public UsuarioDTO ()
  {
  } // ctor

  public UsuarioDTO (String _nombresApellidos, String _identificacion, String _usuario, String _contrasenia, int _tipoUser)
  {
    nombresApellidos = _nombresApellidos;
    identificacion = _identificacion;
    usuario = _usuario;
    contrasenia = _contrasenia;
    tipoUser = _tipoUser;
  } // ctor

    public String getNombresApellidos() {
        return nombresApellidos;
    }

    public void setNombresApellidos(String nombresApellidos) {
        this.nombresApellidos = nombresApellidos;
    }

    public String getIdentificacion() {
        return identificacion;
    }

    public void setIdentificacion(String identificacion) {
        this.identificacion = identificacion;
    }

    public String getUsuario() {
        return usuario;
    }

    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    public String getContrasenia() {
        return contrasenia;
    }

    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }

    public int getTipoUser() {
        return tipoUser;
    }

    public void setTipoUser(int tipoUser) {
        this.tipoUser = tipoUser;
    }
  
  

} // class UsuarioDTO
