package sop_corba;


/**
* sop_corba/UsuarioCllbckIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaces.idl
* viernes 2 de agosto de 2019 08:07:24 PM COT
*/

public interface UsuarioCllbckIntOperations 
{
  String notificar (String codigoAnteproyecto);
} // interface UsuarioCllbckIntOperations
